### ISSUE TITLE
Hi, I want to know whether you can train the model to get the performance described in paper.

### ISSUE THREAD

**Issue by junleiz** [kanchen-usc/GroundeR#2]
Hi, 
Sorry to bother you. I have tried to train the model but I always can not get the satisfactory results. What's more, the training process is slow. I trained the model on  1080 TI. The every epoch costs about 3h !  Thank you!

**Comment by kanchen-usc** [comment]
The training speed is normal. Performance will  basically converge at ~12 epochs, which takes 1.5d. I did not optimize for distributed optimization, and am not clear about the official implementation's speed.
